language: ruby
rvm:
- 2.5.3
install: bundle install --retry=3
before_install:
  - gem update bundler
env:
  - 'TEST_RAILS_VERSION="~> 5.1.6"'
  - 'TEST_RAILS_VERSION="~> 5.2.3"'
  - 'TEST_RAILS_VERSION="~> 6.0.3"'
